### ISSUE TITLE
why so slow on state changes ??? 

### ISSUE THREAD

**Issue by Strike2001** [jghaanstra/nuki.homey#14]
why take actions via web / app / or other devices/user  up to 4 minutes to state update ?? the cloud connection reacts faster than local connection ? i think an individual polling time in the settings failed app v3.0.3 (opener + bridge) , the log is also not correct to that what happens . or not logged .

**Comment by pfreguia** [comment]
Some clarifications:
I did never experienced such a long delays. My Homey runs Nuki Direct and the Nuki app by Athom at the same time and Nuki Direct is always the fastest to reaact to state changes.
 If you start an action from "web", your are not using just the local connection.
Nuki Direct does not uses a polling strategy; it relies on events sent by the Bridge (yes, there is a polling in the app but it is used just for recovering missed notification from the Bridge). 

In order to help you I need to know the steps that lead to such long delay. Thank you.

**Comment by pfreguia** [comment]
Have you experienced the Nuki Direct's slowness in updating the status of the devices in the first few minutes after a restart? If so, I inform you that Nuki Direct may take up to 5 minutes after a restart for the device status to update. The next version (v3.0.5) will update the devices status immediately after the initialization.

**Comment by Strike2001** [comment]
i upgraded to 3.0.5 now the two apps working sync in time . can be closed
