### ISSUE TITLE
moving unlock  latch

### ISSUE THREAD

**Issue by Strike2001** [jghaanstra/nuki.homey#5]
move it to the second ui page off a
device , an at the first which also acts when presses device in overview without funktion, if you use homekit it
is better status messaging , when you remove it you must create a VD as lock must create flows ..... . thx , and for very .... user you can create a VD as lock or switch ... who acts as security protection for the nuki unlatch , an flow if nuki latch unlock and VD not pressed before ( + max time 3 sec ) do nothing otherwise unlock the door . i have a 3 Virtual device as lock create that runs 👌. 

p.s if the unlatch acts not as push button or plug / switch in app , also as lock device handling you must press the device long ui opens , .... 
example opener device in the cloud app . there so many options you can secure your homey. so please don t remove options. Smarthome is not a 0815 thing , a little more power on the brain can help them 😅. 

thx 😊

**Comment by pfreguia** [comment]
The ability to open a door directly from the Homey app user interface has been reintroduced (it was removed in v3.0.3 for security reason). In order to avoid accidental opening the tap gesture has been replaced by a swipe gesture on a slider.
The slider can be hidden in the "Advanced Settings" of the device.
